### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by cjbottaro** [mmmries/jetstream#1]
Can you add to the readme a very basic quickstart guide?

I read through the source code to figure out how to create a stream and a consumer, but I can't figure how to actually start receiving messages. I can `Gnat.pub` to get messages into the stream (verified with `Jetstream.Stream.info`), but yeah, can't consume them.

Thanks.

**Comment by mmmries** [comment]
Hey @cjbottaro I definitely plan to add more documentation to this project, but it's just a for-fun project for me so far. I don't have a lot of time to spend on it since we aren't actually using jetstream at work yet.

I did check locally on my dev machine and it looks like I had a couple of commits that had not yet been pushed up, including a couple of `examples/*` files. I honestly don't remember if these examples were functional at this point or if I was just exploring the API. Feel free to make use of them, but I just wanted to be clear about the state of this code
